import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const categories = [
  {
    name: 'Desarrollo Web',
    slug: 'web-development',
    description: 'Aplicaciones web modernas y escalables con las tecnologías más punteras del mercado.',
    icon: 'Globe',
    order: 1,
    subcategories: [
      {
        name: 'Landing Page',
        slug: 'landing-page',
        description: 'Página única optimizada para conversión. Ideal para campañas, productos o servicios específicos.',
        priceType: 'RANGE',
        minPrice: 800,
        maxPrice: 1500,
        estimatedDays: 10,
        features: [
          'Página única optimizada para conversión',
          'Diseño responsive (mobile-first)',
          'Formulario de captura de leads',
          'SEO básico con meta etiquetas',
          'Open Graph para redes sociales',
          'Optimización Core Web Vitals',
          'Integración con Google Analytics',
          'Hosting incluido (1 año)',
          'Dominio .com incluido (1 año)',
          '2 rondas de revisión incluidas',
          'Soporte 15 días post-lanzamiento',
        ],
        requiresConsulting: false,
        formFields: [
          { label: '¿Tienes diseño previo?', fieldType: 'BOOLEAN', required: true, helpText: 'Si tienes Figma o PSD, podemos ahorrar tiempo', order: 1 },
          { label: '¿Necesitas blog integrado?', fieldType: 'BOOLEAN', required: false, order: 2 },
          { label: 'Objetivo principal de la landing', fieldType: 'TEXTAREA', required: true, placeholder: 'Ej: Captar leads para servicio X', order: 3 },
        ],
      },
      {
        name: 'Web Corporativa',
        slug: 'corporate-website',
        description: 'Presencia digital profesional para tu negocio con CMS integrado.',
        priceType: 'RANGE',
        minPrice: 2000,
        maxPrice: 5000,
        estimatedDays: 25,
        features: [
          '5-10 páginas personalizadas',
          'Diseño responsive (mobile-first)',
          'CMS integrado (gestión de contenido)',
          'Blog con categorías y etiquetas',
          'Formulario de contacto avanzado',
          'SEO técnico completo',
          'Integración Google Analytics + Search Console',
          'Panel de administración',
          'Mapa del sitio XML',
          '2 rondas de revisión incluidas',
          'Soporte 30 días post-lanzamiento',
        ],
        requiresConsulting: false,
        consultingHoursMin: 1,
        consultingHoursMax: 2,
        consultingPrice: 150,
        consultingCriteria: 'Solo si requiere >5 secciones, integración CMS avanzado o multi-idioma',
        formFields: [
          { label: 'Número aproximado de páginas', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 8', order: 1 },
          { label: '¿Necesitas multi-idioma?', fieldType: 'BOOLEAN', required: false, order: 2 },
          { label: '¿Tienes contenido ya preparado?', fieldType: 'BOOLEAN', required: false, order: 3 },
          { label: 'Describe tu negocio y objetivos', fieldType: 'TEXTAREA', required: true, order: 4 },
        ],
        addons: [
          { name: 'Multi-idioma (hasta 3 idiomas)', price: 1500, priceType: 'FIXED' },
          { name: 'Integración con redes sociales', price: 300, priceType: 'FIXED' },
          { name: 'Blog avanzado con newsletter', price: 800, priceType: 'FIXED' },
        ],
      },
      {
        name: 'E-commerce',
        slug: 'ecommerce',
        description: 'Tienda online completa lista para vender. Desde catálogo hasta pasarela de pago.',
        priceType: 'RANGE',
        minPrice: 4000,
        maxPrice: 12000,
        estimatedDays: 50,
        features: [
          'Catálogo de productos (hasta 100)',
          'Carrito de compras completo',
          'Pasarela de pago (Stripe / PayPal)',
          'Panel de administración de pedidos',
          'Gestión de envíos y stock',
          'Notificaciones email transaccionales',
          'Diseño responsive',
          'SEO técnico para producto',
          '2 rondas de revisión incluidas',
          'Soporte 30 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 3,
        consultingHoursMax: 5,
        consultingCriteria: 'Requiere análisis de catálogo, pasarelas de pago, logística e integraciones externas',
        formFields: [
          { label: 'Número aproximado de productos', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 200', order: 1 },
          { label: 'Pasarela de pago preferida', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Stripe', value: 'stripe' }, { label: 'PayPal', value: 'paypal' }, { label: 'Redsys', value: 'redsys' }, { label: 'Aún no lo sé', value: 'unknown' }]), order: 2 },
          { label: '¿Necesitas integración con ERP?', fieldType: 'BOOLEAN', required: false, helpText: 'SAP, Odoo, u otro', order: 3 },
          { label: '¿Tienes catálogo en Excel o CSV?', fieldType: 'BOOLEAN', required: false, order: 4 },
          { label: 'Descripción detallada del proyecto', fieldType: 'TEXTAREA', required: true, order: 5 },
        ],
        addons: [
          { name: 'Integración con ERP', price: 2000, priceType: 'FIXED' },
          { name: 'Catálogo extendido (+100 uds)', price: 500, priceType: 'FIXED' },
          { name: 'Migración desde plataforma actual', price: 1000, priceType: 'FIXED' },
          { name: 'Multi-idioma (hasta 3)', price: 1500, priceType: 'FIXED' },
          { name: 'Diseño de producto 3D', price: 1500, priceType: 'FIXED' },
        ],
      },
      {
        name: 'CRM a Medida',
        slug: 'custom-crm',
        description: 'Sistema de gestión de clientes y ventas completamente personalizado para tu negocio.',
        priceType: 'RANGE',
        minPrice: 6000,
        maxPrice: 18000,
        estimatedDays: 70,
        features: [
          'Gestión de contactos y clientes',
          'Pipeline de ventas personalizable',
          'Panel de indicadores (KPIs)',
          'Roles y permisos de usuario',
          'Integración email (Gmail / Outlook)',
          'Exportación de informes (PDF / CSV)',
          'API para integraciones externas',
          'Importación de datos desde Excel/CSV',
          '2 rondas de revisión incluidas',
          'Soporte 60 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 5,
        consultingHoursMax: 8,
        consultingCriteria: 'Requiere mapeo completo de flujos de trabajo, roles e integraciones con herramientas existentes',
        formFields: [
          { label: 'Número estimado de usuarios del sistema', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 15', order: 1 },
          { label: '¿Usáis algún CRM actualmente?', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'No, empezamos de cero', value: 'none' }, { label: 'Excel / Google Sheets', value: 'sheets' }, { label: 'Otro CRM (especificar)', value: 'other' }]), order: 2 },
          { label: '¿Necesitas app móvil?', fieldType: 'BOOLEAN', required: false, order: 3 },
          { label: 'Describe los flujos de trabajo principales', fieldType: 'TEXTAREA', required: true, order: 4 },
        ],
        addons: [
          { name: 'App móvil (iOS + Android)', price: 6000, priceType: 'FIXED' },
          { name: 'Integración con WhatsApp API', price: 1200, priceType: 'FIXED' },
          { name: 'Módulo de facturación', price: 1500, priceType: 'FIXED' },
          { name: 'Email marketing integrado', price: 1000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Web App / SaaS',
        slug: 'web-app-saas',
        description: 'Aplicación web completa con arquitectura multi-tenant, suscripciones y escalabilidad.',
        priceType: 'RANGE',
        minPrice: 8000,
        maxPrice: 25000,
        estimatedDays: 90,
        features: [
          'Arquitectura multi-tenant',
          'Autenticación y roles (RBAC)',
          'Panel de administración',
          'Suscripciones y facturación recurrente',
          'API RESTful documentada',
          'Documentación de API (Swagger)',
          'Despliegue automatizado (CI/CD)',
          'Tests automatizados',
          '3 rondas de revisión incluidas',
          'Soporte 90 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 5,
        consultingHoursMax: 10,
        consultingCriteria: 'Requiere definir arquitectura, modelo de suscripción, features core y escalabilidad',
        formFields: [
          { label: 'Descripción de la aplicación', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: '¿Tienes modelo de suscripción definido?', fieldType: 'BOOLEAN', required: false, order: 2 },
          { label: 'Usuarios estimados en el primer año', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 1000', order: 3 },
          { label: '¿Necesitas app móvil asociada?', fieldType: 'BOOLEAN', required: false, order: 4 },
        ],
        addons: [
          { name: 'App móvil (iOS + Android)', price: 8000, priceType: 'FIXED' },
          { name: 'Dashboard avanzado con gráficos', price: 2500, priceType: 'FIXED' },
          { name: 'Integración con pasarelas de pago', price: 1500, priceType: 'FIXED' },
          { name: 'Sistema de notificaciones en tiempo real', price: 2000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'MVP',
        slug: 'mvp',
        description: 'Producto mínimo viable para validar tu idea de negocio en el mercado rápidamente.',
        priceType: 'RANGE',
        minPrice: 3000,
        maxPrice: 8000,
        estimatedDays: 30,
        features: [
          'Funcionalidades core del producto',
          'Diseño UI/UX básico',
          'Autenticación de usuarios',
          'API RESTful básica',
          'Base de datos operativa',
          'Despliegue en producción',
          '1 ronda de revisión incluida',
          'Soporte 15 días post-lanzamiento',
          'Documentación técnica básica',
        ],
        requiresConsulting: false,
        consultingHoursMin: 2,
        consultingHoursMax: 4,
        consultingCriteria: 'Solo si no hay documentación técnica ni mockups previos',
        formFields: [
          { label: 'Describe tu idea de negocio', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: '¿Tienes mockups o prototipos?', fieldType: 'BOOLEAN', required: false, order: 2 },
          { label: '¿Cuál es la funcionalidad principal?', fieldType: 'TEXTAREA', required: true, order: 3 },
          { label: 'Fecha ideal de lanzamiento', fieldType: 'TEXT', required: false, placeholder: 'Ej: Diciembre 2026', order: 4 },
        ],
      },
      {
        name: 'Solución Enterprise',
        slug: 'enterprise-solution',
        description: 'Solución integral para grandes empresas con múltiples departamentos y sistemas legacy.',
        priceType: 'STARTING_FROM',
        minPrice: 15000,
        estimatedDays: 120,
        features: [
          'Arquitectura escalable y resiliente',
          'Integración con sistemas legacy',
          'Cumplimiento normativo (GDPR, ISO)',
          'Alta disponibilidad y disaster recovery',
          'SSO y gestión de identidades',
          'Auditoría y logging completo',
          'SLA y soporte prioritario',
          'Formación del equipo interno',
          'Documentación completa',
          'Mantenimiento continuo',
        ],
        requiresConsulting: true,
        consultingHoursMin: 8,
        consultingHoursMax: 10,
        consultingCriteria: 'Obligatorio. Múltiples departamentos, compliance e integraciones legacy requieren análisis profundo',
        formFields: [
          { label: 'Tamaño de la organización (empleados)', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 500', order: 1 },
          { label: 'Sistemas actuales a integrar', fieldType: 'TEXTAREA', required: true, order: 2 },
          { label: 'Requisitos de compliance', fieldType: 'TEXTAREA', required: false, placeholder: 'Ej: GDPR, ISO 27001, etc.', order: 3 },
          { label: 'Descripción detallada del proyecto', fieldType: 'TEXTAREA', required: true, order: 4 },
        ],
      },
      {
        name: 'Mantenimiento Web',
        slug: 'web-maintenance',
        description: 'Plan mensual de mantenimiento, actualizaciones y soporte técnico continuo.',
        priceType: 'RANGE',
        minPrice: 150,
        maxPrice: 500,
        estimatedDays: 1,
        features: [
          'Actualizaciones de seguridad mensuales',
          'Backups semanales',
          'Monitorización 24/7',
          'Soporte técnico por email',
          'Tiempo de respuesta < 24h',
          'Actualizaciones de contenido menores',
          'Informe mensual de rendimiento',
        ],
        requiresConsulting: false,
        formFields: [
          { label: 'URL del sitio web', fieldType: 'TEXT', required: true, order: 1 },
          { label: 'Tecnología actual del sitio', fieldType: 'TEXT', required: true, order: 2 },
          { label: 'Número estimado de visitas mensuales', fieldType: 'NUMBER', required: false, order: 3 },
        ],
        addons: [
          { name: 'Tiempo de respuesta < 4h', price: 200, priceType: 'FIXED' },
          { name: 'Actualizaciones de contenido ilimitadas', price: 150, priceType: 'FIXED' },
          { name: 'Soporte telefónico prioritario', price: 100, priceType: 'FIXED' },
        ],
      },
    ],
  },
  {
    name: 'Desarrollo Mobile',
    slug: 'mobile-development',
    description: 'Apps nativas y multiplataforma para iOS y Android.',
    icon: 'Smartphone',
    order: 2,
    subcategories: [
      {
        name: 'App Básica',
        slug: 'basic-app',
        description: 'Aplicación móvil sencilla con funcionalidades esenciales.',
        priceType: 'RANGE',
        minPrice: 3000,
        maxPrice: 7000,
        estimatedDays: 40,
        features: [
          '3-5 pantallas principales',
          'Navegación principal (tab/drawer)',
          'Consumo de API REST',
          'Diseño nativo (iOS / Android)',
          'Autenticación básica',
          'Publicación en App Store y Google Play',
          '1 ronda de revisión incluida',
          'Soporte 15 días post-lanzamiento',
        ],
        requiresConsulting: false,
        consultingHoursMin: 2,
        consultingHoursMax: 3,
        consultingPrice: 250,
        consultingCriteria: 'Solo si requiere API/backend propio, bases de datos externas o autenticación compleja',
        formFields: [
          { label: 'Plataforma objetivo', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'iOS y Android', value: 'both' }, { label: 'Solo iOS', value: 'ios' }, { label: 'Solo Android', value: 'android' }]), order: 1 },
          { label: 'Describe las funcionalidades principales', fieldType: 'TEXTAREA', required: true, order: 2 },
          { label: '¿Tienes diseño (Figma, Sketch)?', fieldType: 'BOOLEAN', required: false, order: 3 },
        ],
        addons: [
          { name: 'Notificaciones push', price: 800, priceType: 'FIXED' },
          { name: 'Modo offline', price: 1000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'App con API Backend',
        slug: 'app-with-api',
        description: 'Aplicación móvil con backend propio, base de datos y autenticación.',
        priceType: 'RANGE',
        minPrice: 6000,
        maxPrice: 15000,
        estimatedDays: 60,
        features: [
          'App completa + backend personalizado',
          'API RESTful con documentación',
          'Base de datos PostgreSQL',
          'Autenticación con roles',
          'Panel de administración web',
          'Notificaciones push',
          'Publicación en stores',
          '2 rondas de revisión incluidas',
          'Soporte 30 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 3,
        consultingHoursMax: 5,
        consultingCriteria: 'Requiere definir endpoints, modelo de datos y estrategia de autenticación',
        formFields: [
          { label: 'Describe la funcionalidad principal', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: '¿Necesitas tiempo real? (chat, notificaciones)', fieldType: 'BOOLEAN', required: false, order: 2 },
          { label: 'Usuarios estimados', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 5000', order: 3 },
        ],
        addons: [
          { name: 'Chat en tiempo real (WebSockets)', price: 2500, priceType: 'FIXED' },
          { name: 'Dashboard analytics', price: 1500, priceType: 'FIXED' },
        ],
      },
      {
        name: 'App E-commerce',
        slug: 'mobile-ecommerce',
        description: 'Tienda móvil completa con pasarela de pago, notificaciones y seguimiento.',
        priceType: 'RANGE',
        minPrice: 7000,
        maxPrice: 18000,
        estimatedDays: 75,
        features: [
          'Catálogo de productos con búsqueda',
          'Carrito de compras',
          'Pasarela de pago integrada',
          'Notificaciones push de ofertas',
          'Seguimiento de pedidos',
          'Gestión de perfil de usuario',
          'Historial de compras',
          'Publicación en stores',
          '2 rondas de revisión incluidas',
          'Soporte 45 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 4,
        consultingHoursMax: 6,
        consultingCriteria: 'Requiere análisis de pasarelas mobile, notificaciones push y experiencia de compra móvil',
        formFields: [
          { label: 'Número de productos en catálogo', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 500', order: 1 },
          { label: '¿Tienes web e-commerce ya?', fieldType: 'BOOLEAN', required: false, order: 2 },
          { label: 'Pasarela de pago preferida', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Stripe', value: 'stripe' }, { label: 'PayPal', value: 'paypal' }, { label: 'Apple Pay / Google Pay', value: 'wallet' }]), order: 3 },
        ],
        addons: [
          { name: 'Escáner de códigos de barras', price: 1000, priceType: 'FIXED' },
          { name: 'Programa de fidelización', price: 2000, priceType: 'FIXED' },
          { name: 'Realidad aumentada (ver producto)', price: 3000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'App Red Social',
        slug: 'social-media-app',
        description: 'Red social con feed, mensajería, notificaciones y escalabilidad en tiempo real.',
        priceType: 'RANGE',
        minPrice: 10000,
        maxPrice: 25000,
        estimatedDays: 90,
        features: [
          'Feed de contenido personalizado',
          'Mensajería en tiempo real',
          'Perfiles de usuario',
          'Sistema de likes y comentarios',
          'Notificaciones push',
          'Carga de fotos y vídeos',
          'Búsqueda de usuarios',
          'Backend escalable',
          '3 rondas de revisión incluidas',
          'Soporte 60 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 5,
        consultingHoursMax: 8,
        consultingCriteria: 'Requiere diseño detallado del feed, sistema de mensajería y plan de escalabilidad',
        formFields: [
          { label: 'Describe el concepto de la red social', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: 'Usuarios estimados en el primer mes', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 10000', order: 2 },
          { label: '¿Tienes modelo de monetización?', fieldType: 'BOOLEAN', required: false, order: 3 },
        ],
        addons: [
          { name: 'Historias (stories)', price: 3000, priceType: 'FIXED' },
          { name: 'Live streaming', price: 5000, priceType: 'FIXED' },
          { name: 'Monetización con anuncios', price: 4000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'App Enterprise',
        slug: 'enterprise-mobile-app',
        description: 'Solución móvil empresarial con integración a sistemas corporativos y SSO.',
        priceType: 'RANGE',
        minPrice: 15000,
        maxPrice: 40000,
        estimatedDays: 120,
        features: [
          'Integración con sistemas corporativos',
          'SSO y Active Directory',
          'Cumplimiento normativo',
          'Offline first',
          'Sincronización en segundo plano',
          'Dashboard ejecutivo',
          'Soporte multi-idioma',
          '3 rondas de revisión incluidas',
          'Soporte 90 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 8,
        consultingHoursMax: 10,
        consultingCriteria: 'Obligatorio. Múltiples integraciones con sistemas legacy y compliance',
        formFields: [
          { label: 'Sistemas corporativos a integrar', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: '¿Usáis SSO actualmente?', fieldType: 'BOOLEAN', required: false, order: 2 },
          { label: 'Número de empleados usuarios', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 200', order: 3 },
          { label: 'Requisitos de seguridad y compliance', fieldType: 'TEXTAREA', required: true, order: 4 },
        ],
      },
      {
        name: 'MVP Mobile',
        slug: 'mobile-mvp',
        description: 'Producto mínimo viable para validar tu idea de app en el mercado.',
        priceType: 'RANGE',
        minPrice: 3000,
        maxPrice: 8000,
        estimatedDays: 30,
        features: [
          'Funcionalidades core de la app',
          'Diseño UI básico',
          'Autenticación',
          'Publicación en una store',
          'Backend básico si es necesario',
          '1 ronda de revisión incluida',
          'Soporte 15 días post-lanzamiento',
        ],
        requiresConsulting: false,
        consultingHoursMin: 2,
        consultingHoursMax: 4,
        consultingCriteria: 'Solo si requiere backend, autenticación compleja o APIs de terceros',
        formFields: [
          { label: 'Describe tu idea de app', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: 'Funcionalidad principal (la que valida tu idea)', fieldType: 'TEXTAREA', required: true, order: 2 },
          { label: '¿Tienes prototipo?', fieldType: 'BOOLEAN', required: false, order: 3 },
        ],
      },
    ],
  },
  {
    name: 'Inteligencia Artificial',
    slug: 'artificial-intelligence',
    description: 'Soluciones de IA para automatizar, optimizar y transformar tu negocio.',
    icon: 'Brain',
    order: 3,
    subcategories: [
      {
        name: 'Chatbot / Asistente IA',
        slug: 'ai-chatbot',
        description: 'Asistente virtual inteligente para atención al cliente, soporte técnico o ventas.',
        priceType: 'RANGE',
        minPrice: 2000,
        maxPrice: 7000,
        estimatedDays: 25,
        features: [
          'Integración web / WhatsApp / Telegram',
          'Procesamiento de lenguaje natural (NLP)',
          'Base de conocimiento personalizable',
          'Handover a agente humano',
          'Analytics de conversaciones',
          'Multilingüe',
          '1 ronda de revisión incluida',
          'Soporte 30 días post-lanzamiento',
        ],
        requiresConsulting: false,
        consultingHoursMin: 2,
        consultingHoursMax: 4,
        consultingCriteria: 'Solo si requiere RAG, fine-tuning o integración con APIs externas complejas',
        formFields: [
          { label: 'Canal principal', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Web', value: 'web' }, { label: 'WhatsApp', value: 'whatsapp' }, { label: 'Telegram', value: 'telegram' }, { label: 'Múltiples canales', value: 'multi' }]), order: 1 },
          { label: 'Volumen estimado de conversaciones/mes', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 1000', order: 2 },
          { label: 'Describe los temas que debe cubrir', fieldType: 'TEXTAREA', required: true, order: 3 },
        ],
        addons: [
          { name: 'Integración con base de datos propia (RAG)', price: 2000, priceType: 'FIXED' },
          { name: 'Fine-tuning con tus datos', price: 3000, priceType: 'FIXED' },
          { name: 'Panel de analytics avanzado', price: 1000, priceType: 'FIXED' },
          { name: 'Soporte multilingüe (+3 idiomas)', price: 1000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Automatización de Procesos',
        slug: 'process-automation',
        description: 'Automatización inteligente de procesos repetitivos con IA.',
        priceType: 'RANGE',
        minPrice: 3000,
        maxPrice: 10000,
        estimatedDays: 45,
        features: [
          'Mapeo de procesos actuales',
          'Diseño de flujo automatizado',
          'Integración con APIs existentes',
          'Paneles de monitoreo',
          'Reportes de eficiencia',
          'Gestión de excepciones',
          '2 rondas de revisión incluidas',
          'Soporte 45 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 3,
        consultingHoursMax: 5,
        consultingCriteria: 'Requiere mapear procesos actuales, identificar cuellos de botella y diseñar integraciones',
        formFields: [
          { label: 'Describe los procesos a automatizar', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: 'Volumen mensual de operaciones', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 10000', order: 2 },
          { label: '¿Qué sistemas están involucrados?', fieldType: 'TEXTAREA', required: true, order: 3 },
        ],
        addons: [
          { name: 'Integración con ERP/SAP', price: 3000, priceType: 'FIXED' },
          { name: 'Dashboard en tiempo real', price: 1500, priceType: 'FIXED' },
          { name: 'ROI calculator incluido', price: 500, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Sistema de Recomendación',
        slug: 'recommendation-system',
        description: 'Motor de recomendaciones inteligente para contenido, productos o servicios.',
        priceType: 'RANGE',
        minPrice: 4000,
        maxPrice: 12000,
        estimatedDays: 45,
        features: [
          'Motor de recomendaciones basado en ML',
          'Filtrado colaborativo y basado en contenido',
          'API de recomendaciones en tiempo real',
          'Dashboard de rendimiento de recomendaciones',
          'A/B testing integrado',
          '2 rondas de revisión incluidas',
          'Soporte 45 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 4,
        consultingHoursMax: 6,
        consultingCriteria: 'Se necesita analizar fuentes de datos, algoritmos y la infraestructura de entrenamiento',
        formFields: [
          { label: 'Describe los items a recomendar', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: 'Volumen de items en catálogo', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 50000', order: 2 },
          { label: 'Usuarios activos estimados', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 100000', order: 3 },
        ],
        addons: [
          { name: 'Personalización en tiempo real', price: 2500, priceType: 'FIXED' },
          { name: 'Recomendaciones contextuales (geo, hora)', price: 1500, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Análisis NLP',
        slug: 'nlp-analysis',
        description: 'Procesamiento de lenguaje natural para analizar textos, opiniones y documentos.',
        priceType: 'RANGE',
        minPrice: 3000,
        maxPrice: 10000,
        estimatedDays: 35,
        features: [
          'Análisis de sentimientos',
          'Clasificación de textos',
          'Extracción de entidades (NER)',
          'Resumen automático de textos',
          'API RESTful para integración',
          'Dashboard de resultados',
          '2 rondas de revisión incluidas',
          'Soporte 30 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 3,
        consultingHoursMax: 5,
        consultingCriteria: 'Requiere analizar volumen de datos, idiomas, precisión requerida y pipeline de procesamiento',
        formFields: [
          { label: 'Volumen de textos a procesar', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 100000 documentos/mes', order: 1 },
          { label: 'Idiomas a procesar', fieldType: 'TEXT', required: true, placeholder: 'Ej: Español, Inglés', order: 2 },
          { label: 'Describe el caso de uso', fieldType: 'TEXTAREA', required: true, order: 3 },
        ],
        addons: [
          { name: 'Procesamiento en tiempo real', price: 2000, priceType: 'FIXED' },
          { name: 'Modelo entrenado con tus datos', price: 3000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Visión por Computadora',
        slug: 'computer-vision',
        description: 'Sistemas de reconocimiento de imágenes, detección de objetos y análisis visual.',
        priceType: 'RANGE',
        minPrice: 5000,
        maxPrice: 15000,
        estimatedDays: 70,
        features: [
          'Detección y clasificación de objetos',
          'Reconocimiento facial / de patrones',
          'Procesamiento en tiempo real',
          'API RESTful para integración',
          'Dashboard de resultados',
          '2 rondas de revisión incluidas',
          'Soporte 60 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 5,
        consultingHoursMax: 8,
        consultingCriteria: 'Requiere evaluar calidad y volumen de imágenes, modelos base y requerimientos de hardware',
        formFields: [
          { label: 'Describe el caso de uso', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: 'Volumen de imágenes a procesar/día', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 1000', order: 2 },
          { label: '¿Necesitas procesamiento en tiempo real?', fieldType: 'BOOLEAN', required: false, order: 3 },
        ],
        addons: [
          { name: 'Entrenamiento de modelo personalizado', price: 5000, priceType: 'FIXED' },
          { name: 'Integración con cámaras IP', price: 2000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Fine-tuning de Modelos',
        slug: 'model-fine-tuning',
        description: 'Adaptación de modelos LLM base con tus datos para mejorar precisión en tu dominio.',
        priceType: 'RANGE',
        minPrice: 2000,
        maxPrice: 8000,
        estimatedDays: 25,
        features: [
          'Selección del modelo base óptimo',
          'Preparación y limpieza del dataset',
          'Entrenamiento del modelo',
          'Evaluación de rendimiento',
          'API desplegada',
          'Documentación del modelo',
          '1 ronda de revisión incluida',
          'Soporte 30 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 3,
        consultingHoursMax: 5,
        consultingCriteria: 'Requiere evaluar dataset, métricas de éxito y coste computacional',
        formFields: [
          { label: 'Describe el caso de uso del modelo', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: 'Tamaño estimado del dataset', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 10000 muestras', order: 2 },
          { label: 'Modelo base preferido', fieldType: 'SELECT', required: false, options: JSON.stringify([{ label: 'GPT-4', value: 'gpt4' }, { label: 'Llama 3', value: 'llama3' }, { label: 'Mistral', value: 'mistral' }, { label: 'A decidir en consultoría', value: 'unknown' }]), order: 3 },
        ],
        addons: [
          { name: 'Despliegue on-premise', price: 3000, priceType: 'FIXED' },
          { name: 'Pipeline de actualización continua', price: 2000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Solución IA Personalizada',
        slug: 'custom-ai-solution',
        description: 'Solución completa de IA desde el análisis hasta el despliegue, adaptada a tus necesidades.',
        priceType: 'STARTING_FROM',
        minPrice: 10000,
        estimatedDays: 90,
        features: [
          'Análisis de viabilidad técnica',
          'Diseño de arquitectura IA',
          'Recolección y preparación de datos',
          'Entrenamiento y evaluación',
          'Despliegue en producción',
          'Dashboard de monitoreo',
          'Documentación completa',
          'Formación del equipo',
          '3 rondas de revisión incluidas',
          'Soporte 90 días post-lanzamiento',
        ],
        requiresConsulting: true,
        consultingHoursMin: 8,
        consultingHoursMax: 10,
        consultingCriteria: 'Obligatorio. Stack completo desde datos hasta despliegue requiere análisis profundo',
        formFields: [
          { label: 'Describe el problema a resolver con IA', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: '¿Tienes datos disponibles?', fieldType: 'BOOLEAN', required: true, order: 2 },
          { label: 'Volumen y tipo de datos', fieldType: 'TEXTAREA', required: true, placeholder: 'Ej: 1TB de imágenes etiquetadas', order: 3 },
          { label: 'Restricciones de infraestructura', fieldType: 'TEXTAREA', required: false, placeholder: 'Ej: On-premise obligatorio', order: 4 },
        ],
      },
    ],
  },
  {
    name: 'Cloud & DevOps',
    slug: 'cloud-devops',
    description: 'Infraestructura cloud escalable, automatización de despliegues y operaciones.',
    icon: 'Cloud',
    order: 4,
    subcategories: [
      {
        name: 'Migración a la Nube',
        slug: 'cloud-migration',
        description: 'Migración de tu infraestructura actual a AWS, GCP o Azure de forma segura y planificada.',
        priceType: 'RANGE',
        minPrice: 2000,
        maxPrice: 8000,
        estimatedDays: 30,
        features: [
          'Inventario de recursos actuales',
          'Estrategia de migración (lift & shift / re-architect)',
          'Migración de datos',
          'Configuración de seguridad',
          'Documentación de la nueva arquitectura',
          'Plan de rollback',
          '2 rondas de revisión incluidas',
          'Soporte 30 días post-migración',
        ],
        requiresConsulting: true,
        consultingHoursMin: 3,
        consultingHoursMax: 5,
        consultingCriteria: 'Requiere inventariar recursos, analizar dependencias y definir estrategia de migración',
        formFields: [
          { label: 'Proveedor cloud destino', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'AWS', value: 'aws' }, { label: 'Google Cloud', value: 'gcp' }, { label: 'Azure', value: 'azure' }, { label: 'A definir', value: 'unknown' }]), order: 1 },
          { label: 'Describe tu infraestructura actual', fieldType: 'TEXTAREA', required: true, order: 2 },
          { label: 'Número de servidores/servicios', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 15', order: 3 },
        ],
        addons: [
          { name: 'Formación del equipo post-migración', price: 1500, priceType: 'FIXED' },
          { name: 'Optimización de costes cloud', price: 1000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'CI/CD Pipeline',
        slug: 'cicd-pipeline',
        description: 'Automatización de integración y despliegue continuo para entregar software más rápido.',
        priceType: 'RANGE',
        minPrice: 1500,
        maxPrice: 5000,
        estimatedDays: 15,
        features: [
          'Repositorio Git configurado',
          'Integración continua automatizada',
          'Despliegue continuo (staging + producción)',
          'Tests automatizados en pipeline',
          'Notificaciones de estado',
          'Rollback automático',
          'Documentación del pipeline',
          'Soporte 15 días post-implementación',
        ],
        requiresConsulting: false,
        consultingHoursMin: 1,
        consultingHoursMax: 3,
        consultingCriteria: 'Solo si el proyecto tiene múltiples servicios o equipos trabajando en paralelo',
        formFields: [
          { label: 'Stack tecnológico actual', fieldType: 'TEXT', required: true, placeholder: 'Ej: Node.js + React + PostgreSQL', order: 1 },
          { label: '¿Usáis Git actualmente?', fieldType: 'BOOLEAN', required: true, order: 2 },
          { label: 'Entornos necesarios', fieldType: 'TEXT', required: false, placeholder: 'Ej: dev, staging, producción', order: 3 },
        ],
        addons: [
          { name: 'Integración con Docker', price: 800, priceType: 'FIXED' },
          { name: 'Despliegue multi-entorno avanzado', price: 1000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Infraestructura como Código',
        slug: 'infrastructure-as-code',
        description: 'Gestión de infraestructura cloud mediante código (Terraform, Pulumi, CDK).',
        priceType: 'RANGE',
        minPrice: 2000,
        maxPrice: 6000,
        estimatedDays: 20,
        features: [
          'Definición de infraestructura como código',
          'Terraform / Pulumi / CDK',
          'Control de versiones de infraestructura',
          'Entornos replicables',
          'Documentación técnica',
          'Soporte 20 días post-implementación',
        ],
        requiresConsulting: false,
        consultingHoursMin: 2,
        consultingHoursMax: 4,
        consultingCriteria: 'Solo para entornos multi-cluster, multi-región o con requisitos de compliance',
        formFields: [
          { label: 'Proveedor cloud', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'AWS', value: 'aws' }, { label: 'Google Cloud', value: 'gcp' }, { label: 'Azure', value: 'azure' }]), order: 1 },
          { label: 'Servicios a gestionar como código', fieldType: 'TEXTAREA', required: true, order: 2 },
        ],
        addons: [
          { name: 'Módulos reutilizables', price: 1000, priceType: 'FIXED' },
          { name: 'Pipeline de validación de infraestructura', price: 800, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Monitoreo y Observabilidad',
        slug: 'monitoring-observability',
        description: 'Sistema completo de monitoreo, alertas y observabilidad para tu infraestructura.',
        priceType: 'RANGE',
        minPrice: 1500,
        maxPrice: 5000,
        estimatedDays: 15,
        features: [
          'Monitoreo de infraestructura y aplicación',
          'Alertas configurables',
          'Dashboards personalizados',
          'Logs centralizados',
          'Trazabilidad distribuida (tracing)',
          'Documentación del sistema',
          'Soporte 15 días post-implementación',
        ],
        requiresConsulting: false,
        consultingHoursMin: 1,
        consultingHoursMax: 3,
        consultingCriteria: 'Solo para sistemas distribuidos o basados en microservicios',
        formFields: [
          { label: 'Stack tecnológico a monitorear', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: '¿Usáis ya alguna herramienta?', fieldType: 'TEXT', required: false, placeholder: 'Ej: CloudWatch, Datadog', order: 2 },
        ],
        addons: [
          { name: 'Integración con PagerDuty/Opsgenie', price: 500, priceType: 'FIXED' },
          { name: 'SLO/SLI tracking', price: 800, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Arquitectura Cloud Completa',
        slug: 'cloud-architecture',
        description: 'Diseño e implementación de arquitectura cloud completa: red, seguridad, costes y escalado.',
        priceType: 'RANGE',
        minPrice: 5000,
        maxPrice: 15000,
        estimatedDays: 45,
        features: [
          'Diseño de arquitectura completo',
          'Red y segmentación (VPC, subnets)',
          'Seguridad perimetral (WAF, Shield)',
          'Auto-scaling y balanceo',
          'Optimización de costes',
          'Documentación de arquitectura',
          '2 rondas de revisión incluidas',
          'Soporte 60 días post-implementación',
        ],
        requiresConsulting: true,
        consultingHoursMin: 5,
        consultingHoursMax: 8,
        consultingCriteria: 'Requiere diseño completo de red, seguridad, costes y estrategia de escalado',
        formFields: [
          { label: 'Proveedor cloud', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'AWS', value: 'aws' }, { label: 'Google Cloud', value: 'gcp' }, { label: 'Azure', value: 'azure' }]), order: 1 },
          { label: 'Carga estimada (peticiones/día)', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 1000000', order: 2 },
          { label: 'Requisitos de compliance', fieldType: 'TEXTAREA', required: false, order: 3 },
        ],
        addons: [
          { name: 'Disaster Recovery plan', price: 2000, priceType: 'FIXED' },
          { name: 'Multi-región activo-activo', price: 3000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Consultoría DevOps',
        slug: 'devops-consulting',
        description: 'Consultoría bajo demanda en estrategia DevOps, herramientas y mejores prácticas.',
        priceType: 'HOURLY',
        minPrice: 100,
        maxPrice: 200,
        estimatedDays: 1,
        features: [
          'Sesiones de consultoría bajo demanda',
          'Revisión de prácticas actuales',
          'Recomendaciones personalizadas',
          'Plan de acción detallado',
          'Soporte por hora contratada',
        ],
        requiresConsulting: false,
        formFields: [
          { label: 'Área de enfoque', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Infraestructura cloud', value: 'infra' }, { label: 'CI/CD', value: 'cicd' }, { label: 'Seguridad', value: 'security' }, { label: 'General', value: 'general' }]), order: 1 },
          { label: 'Describe el contexto y objetivos', fieldType: 'TEXTAREA', required: true, order: 2 },
        ],
      },
    ],
  },
  {
    name: 'Consultoría Tecnológica',
    slug: 'tech-consulting',
    description: 'Asesoramiento estratégico en tecnología para transformar tu negocio.',
    icon: 'Lightbulb',
    order: 5,
    subcategories: [
      {
        name: 'Auditoría Técnica',
        slug: 'technical-audit',
        description: 'Revisión exhaustiva de tu código, arquitectura y prácticas de desarrollo.',
        priceType: 'RANGE',
        minPrice: 1000,
        maxPrice: 3000,
        estimatedDays: 10,
        features: [
          'Revisión de código completa',
          'Análisis de deuda técnica',
          'Informe de vulnerabilidades',
          'Recomendaciones de mejora',
          'Estimación de esfuerzo correctivo',
          'Sesión de presentación de resultados',
          'Plan de acción priorizado',
        ],
        requiresConsulting: false,
        consultingHoursMin: 2,
        consultingHoursMax: 4,
        consultingCriteria: 'Solo si el código base supera 50k líneas o son múltiples repositorios',
        formFields: [
          { label: 'URL del repositorio', fieldType: 'TEXT', required: true, order: 1 },
          { label: 'Stack tecnológico', fieldType: 'TEXT', required: true, placeholder: 'Ej: NestJS + React + PostgreSQL', order: 2 },
          { label: 'Líneas de código estimadas', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 50000', order: 3 },
          { label: 'Áreas específicas a revisar', fieldType: 'TEXTAREA', required: false, order: 4 },
        ],
        addons: [
          { name: 'Informe ejecutivo para stakeholders', price: 500, priceType: 'FIXED' },
          { name: 'Auditoría de seguridad avanzada (OWASP)', price: 1000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Arquitectura de Software',
        slug: 'software-architecture',
        description: 'Diseño de arquitectura software robusta, escalable y mantenible.',
        priceType: 'RANGE',
        minPrice: 2000,
        maxPrice: 5000,
        estimatedDays: 20,
        features: [
          'Definición de arquitectura objetivo',
          'Selección de stack tecnológico',
          'Diagramas C4 model',
          'Decisiones de diseño documentadas (ADR)',
          'Plan de migración si aplica',
          'Sesión de validación con el equipo',
          'Documentación completa',
        ],
        requiresConsulting: true,
        consultingHoursMin: 3,
        consultingHoursMax: 5,
        consultingCriteria: 'Requiere entender restricciones técnicas, stack actual y necesidades de escalabilidad',
        formFields: [
          { label: 'Describe el proyecto y sus objetivos', fieldType: 'TEXTAREA', required: true, order: 1 },
          { label: 'Stack tecnológico actual', fieldType: 'TEXT', required: true, order: 2 },
          { label: 'Usuarios concurrentes estimados', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 10000', order: 3 },
          { label: 'Restricciones técnicas conocidas', fieldType: 'TEXTAREA', required: false, order: 4 },
        ],
        addons: [
          { name: 'MVP de prueba de concepto', price: 2000, priceType: 'FIXED' },
          { name: 'Benchmarking de rendimiento', price: 1500, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Estrategia Digital',
        slug: 'digital-strategy',
        description: 'Hoja de ruta tecnológica alineada con los objetivos de negocio.',
        priceType: 'RANGE',
        minPrice: 1500,
        maxPrice: 5000,
        estimatedDays: 20,
        features: [
          'Análisis de situación actual',
          'Definición de objetivos tecnológicos',
          'Hoja de ruta (roadmap)',
          'Análisis coste-beneficio',
          'Recomendaciones de proveedores',
          'Plan de adopción',
          'Documentación ejecutiva',
          'Sesión de presentación',
        ],
        requiresConsulting: true,
        consultingHoursMin: 3,
        consultingHoursMax: 5,
        consultingCriteria: 'Requiere entender la organización, canales y presupuesto disponible',
        formFields: [
          { label: 'Tamaño de la organización', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 50 empleados', order: 1 },
          { label: 'Sector / Industria', fieldType: 'TEXT', required: true, order: 2 },
          { label: 'Objetivos principales', fieldType: 'TEXTAREA', required: true, order: 3 },
          { label: 'Presupuesto estimado para el proyecto', fieldType: 'SELECT', required: false, options: JSON.stringify([{ label: '< 10.000€', value: 'small' }, { label: '10.000 - 50.000€', value: 'medium' }, { label: '50.000 - 100.000€', value: 'large' }, { label: '> 100.000€', value: 'enterprise' }]), order: 4 },
        ],
        addons: [
          { name: 'Análisis competitivo', price: 1000, priceType: 'FIXED' },
          { name: 'Taller de innovación con el equipo', price: 1500, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Code Review',
        slug: 'code-review',
        description: 'Revisión de código por expertos para garantizar calidad y mejores prácticas.',
        priceType: 'RANGE',
        minPrice: 500,
        maxPrice: 2000,
        estimatedDays: 5,
        features: [
          'Revisión línea por línea',
          'Detección de code smells',
          'Recomendaciones de refactorización',
          'Buenas prácticas del lenguaje',
          'Informe detallado',
          'Sesión de feedback',
        ],
        requiresConsulting: false,
        formFields: [
          { label: 'URL del repositorio', fieldType: 'TEXT', required: true, order: 1 },
          { label: 'Áreas a enfocar la revisión', fieldType: 'TEXTAREA', required: false, order: 2 },
          { label: 'Lenguaje / Framework', fieldType: 'TEXT', required: true, order: 3 },
        ],
        addons: [
          { name: 'Review de seguridad', price: 500, priceType: 'FIXED' },
          { name: 'Review de rendimiento', price: 500, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Transformación Digital',
        slug: 'digital-transformation',
        description: 'Acompañamiento completo en la transformación digital de tu organización.',
        priceType: 'RANGE',
        minPrice: 5000,
        maxPrice: 20000,
        estimatedDays: 60,
        features: [
          'Diagnóstico de madurez digital',
          'Definición de estrategia',
          'Selección de tecnologías',
          'Plan de cambio y formación',
          'Acompañamiento en implementación',
          'Métricas de éxito (OKRs)',
          'Documentación completa',
          'Sesiones de formación',
          'Soporte continuo durante la transformación',
        ],
        requiresConsulting: true,
        consultingHoursMin: 5,
        consultingHoursMax: 10,
        consultingCriteria: 'Obligatorio. Múltiples departamentos, sistemas legacy y cambio cultural requieren análisis profundo',
        formFields: [
          { label: 'Tamaño de la organización', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 200 empleados', order: 1 },
          { label: 'Áreas/departamentos involucrados', fieldType: 'TEXTAREA', required: true, order: 2 },
          { label: 'Sistemas actuales críticos', fieldType: 'TEXTAREA', required: true, order: 3 },
          { label: 'Plazo estimado para la transformación', fieldType: 'TEXT', required: false, placeholder: 'Ej: 12 meses', order: 4 },
          { label: 'Principales desafíos actuales', fieldType: 'TEXTAREA', required: true, order: 5 },
        ],
        addons: [
          { name: 'Formación executive para directivos', price: 2000, priceType: 'FIXED' },
          { name: 'Change management program', price: 3000, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Consultoría Senior',
        slug: 'senior-consulting',
        description: 'Consultoría bajo demanda con expertos senior en tecnología y arquitectura.',
        priceType: 'HOURLY',
        minPrice: 120,
        maxPrice: 200,
        estimatedDays: 1,
        features: [
          'Sesiones de consultoría bajo demanda',
          'Experto senior con 10+ años de experiencia',
          'Resolución de problemas específicos',
          'Recomendaciones prácticas y aplicables',
          'Soporte por hora contratada',
        ],
        requiresConsulting: false,
        formFields: [
          { label: 'Área de consultoría', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Arquitectura', value: 'architecture' }, { label: 'Estrategia técnica', value: 'strategy' }, { label: 'Revisión de proyecto', value: 'review' }, { label: 'Mentoría técnica', value: 'mentoring' }, { label: 'Otro', value: 'other' }]), order: 1 },
          { label: 'Describe el contexto y objetivos', fieldType: 'TEXTAREA', required: true, order: 2 },
        ],
      },
    ],
  },
  {
    name: 'Clases y Mentorías',
    slug: 'classes-mentoring',
    description: 'Formación técnica y mentoría personalizada para desarrollar tu talento digital.',
    icon: 'GraduationCap',
    order: 6,
    subcategories: [
      {
        name: 'Mentoría 1:1 (Sesión)',
        slug: 'mentoring-session',
        description: 'Sesión individual de mentoría técnica con un experto. Ideal para resolver dudas específicas o avanzar en tu carrera.',
        priceType: 'FIXED',
        basePrice: 80,
        estimatedDays: 1,
        features: [
          'Sesión de 60 minutos por videollamada',
          'Preparación de temario personalizado',
          'Ejercicios prácticos',
          'Repositorio con recursos',
          'Seguimiento de progreso',
          'Grabación de la sesión disponible',
        ],
        requiresConsulting: false,
        formFields: [
          { label: 'Tecnología / Área de interés', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'React / Next.js', value: 'react' }, { label: 'Node.js / NestJS', value: 'node' }, { label: 'TypeScript', value: 'typescript' }, { label: 'DevOps / Cloud', value: 'devops' }, { label: 'Arquitectura de Software', value: 'architecture' }, { label: 'Preparación de entrevistas', value: 'interviews' }, { label: 'Otro', value: 'other' }]), order: 1 },
          { label: 'Describe tus objetivos para la sesión', fieldType: 'TEXTAREA', required: true, order: 2 },
          { label: 'Nivel actual', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Junior (0-2 años)', value: 'junior' }, { label: 'Mid (2-5 años)', value: 'mid' }, { label: 'Senior (5+ años)', value: 'senior' }]), order: 3 },
        ],
      },
      {
        name: 'Pack Mentoría (5 sesiones)',
        slug: 'mentoring-pack-5',
        description: 'Programa de mentoría completa con 5 sesiones para un progreso continuo y medible.',
        priceType: 'FIXED',
        basePrice: 350,
        estimatedDays: 35,
        features: [
          '5 sesiones de 60 minutos',
          'Plan de desarrollo personalizado',
          'Ejercicios entre sesiones',
          'Repositorio privado con recursos',
          'Seguimiento por chat',
          'Grabaciones disponibles',
          'Certificado de finalización',
        ],
        requiresConsulting: false,
        formFields: [
          { label: 'Tecnología / Área de interés', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'React / Next.js', value: 'react' }, { label: 'Node.js / NestJS', value: 'node' }, { label: 'TypeScript', value: 'typescript' }, { label: 'DevOps / Cloud', value: 'devops' }, { label: 'Arquitectura de Software', value: 'architecture' }, { label: 'Preparación de entrevistas', value: 'interviews' }, { label: 'Full-stack', value: 'fullstack' }, { label: 'Otro', value: 'other' }]), order: 1 },
          { label: 'Objetivos a largo plazo', fieldType: 'TEXTAREA', required: true, order: 2 },
          { label: 'Nivel actual', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Junior (0-2 años)', value: 'junior' }, { label: 'Mid (2-5 años)', value: 'mid' }, { label: 'Senior (5+ años)', value: 'senior' }]), order: 3 },
        ],
      },
      {
        name: 'Pack Mentoría (10 sesiones)',
        slug: 'mentoring-pack-10',
        description: 'Programa intensivo de mentoría con 10 sesiones para un cambio de nivel real en tu carrera.',
        priceType: 'FIXED',
        basePrice: 600,
        estimatedDays: 70,
        features: [
          '10 sesiones de 60 minutos',
          'Plan de desarrollo completo',
          'Proyecto práctico guiado',
          'Ejercicios y challenges semanales',
          'Repositorio privado con recursos',
          'Seguimiento prioritario por chat',
          'Grabaciones disponibles',
          'Certificado de finalización',
          'Carta de recomendación',
        ],
        requiresConsulting: false,
        formFields: [
          { label: 'Tecnología / Área de interés', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'React / Next.js', value: 'react' }, { label: 'Node.js / NestJS', value: 'node' }, { label: 'TypeScript', value: 'typescript' }, { label: 'DevOps / Cloud', value: 'devops' }, { label: 'Arquitectura de Software', value: 'architecture' }, { label: 'Full-stack', value: 'fullstack' }]), order: 1 },
          { label: 'Objetivos del programa', fieldType: 'TEXTAREA', required: true, order: 2 },
          { label: 'Proyecto que te gustaría construir', fieldType: 'TEXTAREA', required: false, order: 3 },
          { label: 'Nivel actual', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Junior (0-2 años)', value: 'junior' }, { label: 'Mid (2-5 años)', value: 'mid' }, { label: 'Senior (5+ años)', value: 'senior' }]), order: 4 },
        ],
      },
      {
        name: 'Formación para Equipos',
        slug: 'team-training',
        description: 'Programa de formación a medida para tu equipo técnico en tecnologías modernas.',
        priceType: 'RANGE',
        minPrice: 1000,
        maxPrice: 4000,
        estimatedDays: 15,
        features: [
          'Evaluación del nivel del equipo',
          'Temario personalizado',
          'Sesiones en vivo (presencial o remoto)',
          'Ejercicios prácticos grupales',
          'Proyecto final en equipo',
          'Material didáctico incluido',
          'Soporte post-formación (2 semanas)',
          'Certificados individuales',
        ],
        requiresConsulting: true,
        consultingHoursMin: 2,
        consultingHoursMax: 3,
        consultingCriteria: 'Requiere evaluar nivel del equipo, definir temario a medida y objetivos',
        formFields: [
          { label: 'Tecnología a formar', fieldType: 'TEXT', required: true, order: 1 },
          { label: 'Número de participantes', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 10', order: 2 },
          { label: 'Nivel actual del equipo', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Junior', value: 'junior' }, { label: 'Mid', value: 'mid' }, { label: 'Senior', value: 'senior' }, { label: 'Mixto', value: 'mixed' }]), order: 3 },
          { label: 'Objetivos de la formación', fieldType: 'TEXTAREA', required: true, order: 4 },
          { label: 'Duración estimada deseada', fieldType: 'SELECT', required: false, options: JSON.stringify([{ label: '1 día (intensivo)', value: '1day' }, { label: '1 semana', value: '1week' }, { label: '2 semanas', value: '2weeks' }, { label: '1 mes', value: '1month' }]), order: 5 },
        ],
        addons: [
          { name: 'Material premium (ejercicios + soluciones)', price: 500, priceType: 'FIXED' },
          { name: 'Sesiones de seguimiento post-formación', price: 800, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Bootcamp Intensivo',
        slug: 'intensive-bootcamp',
        description: 'Bootcamp inmersivo para dominar una tecnología en tiempo récord.',
        priceType: 'RANGE',
        minPrice: 2000,
        maxPrice: 6000,
        estimatedDays: 20,
        features: [
          'Programa intensivo de inmersión total',
          'Proyecto real del principio al fin',
          'Mentoría diaria',
          'Code reviews continuos',
          'Preparación para certificación',
          'Material didáctico completo',
          'Comunidad privada de alumnos',
          'Certificado de finalización',
          'Bolsa de trabajo / conexiones',
        ],
        requiresConsulting: true,
        consultingHoursMin: 2,
        consultingHoursMax: 4,
        consultingCriteria: 'Requiere definir temario exacto, duración y proyecto práctico',
        formFields: [
          { label: 'Tecnología del bootcamp', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'React & Next.js Avanzado', value: 'react' }, { label: 'Node.js & NestJS Backend', value: 'node' }, { label: 'Full-stack TypeScript', value: 'fullstack' }, { label: 'DevOps & Cloud', value: 'devops' }, { label: 'Arquitectura de Software', value: 'architecture' }]), order: 1 },
          { label: 'Número de participantes', fieldType: 'NUMBER', required: true, placeholder: 'Ej: 15', order: 2 },
          { label: 'Nivel mínimo requerido', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Junior con bases', value: 'junior' }, { label: 'Mid-level', value: 'mid' }, { label: 'Senior', value: 'senior' }]), order: 3 },
          { label: 'Objetivos del bootcamp', fieldType: 'TEXTAREA', required: true, order: 4 },
        ],
        addons: [
          { name: 'Certificación oficial incluida', price: 1000, priceType: 'FIXED' },
          { name: 'Sesiones 1:1 adicionales', price: 500, priceType: 'FIXED' },
        ],
      },
      {
        name: 'Code Review + Feedback',
        slug: 'code-review-feedback',
        description: 'Revisión personalizada de tu código con feedback detallado para mejorar tus habilidades.',
        priceType: 'RANGE',
        minPrice: 200,
        maxPrice: 500,
        estimatedDays: 5,
        features: [
          'Revisión detallada de tu código',
          'Feedback línea por línea',
          'Sugerencias de mejora concretas',
          'Ejemplos de código corregido',
          'Sesión de video para explicar cambios',
          'Guía de buenas prácticas personalizada',
        ],
        requiresConsulting: false,
        formFields: [
          { label: 'URL del repositorio', fieldType: 'TEXT', required: true, order: 1 },
          { label: 'Lenguaje / Framework', fieldType: 'TEXT', required: true, order: 2 },
          { label: 'Áreas específicas de mejora', fieldType: 'TEXTAREA', required: false, order: 3 },
          { label: 'Nivel actual', fieldType: 'SELECT', required: true, options: JSON.stringify([{ label: 'Junior', value: 'junior' }, { label: 'Mid', value: 'mid' }, { label: 'Senior', value: 'senior' }]), order: 4 },
        ],
        addons: [
          { name: 'Sesión 1:1 para resolver dudas', price: 80, priceType: 'FIXED' },
          { name: 'Segunda revisión del código corregido', price: 150, priceType: 'FIXED' },
        ],
      },
    ],
  },
];

async function main() {
  console.log('Seeding database...');

  for (const cat of categories) {
    const category = await prisma.serviceCategory.create({
      data: {
        name: cat.name,
        slug: cat.slug,
        description: cat.description,
        icon: cat.icon,
        order: cat.order,
        subcategories: {
          create: cat.subcategories.map((sub) => ({
            name: sub.name,
            slug: sub.slug,
            description: sub.description,
            priceType: sub.priceType,
            basePrice: sub.basePrice || null,
            minPrice: sub.minPrice || null,
            maxPrice: sub.maxPrice || null,
            estimatedDays: sub.estimatedDays || null,
            features: sub.features,
            requiresConsulting: sub.requiresConsulting,
            consultingHoursMin: sub.consultingHoursMin || null,
            consultingHoursMax: sub.consultingHoursMax || null,
            consultingPrice: sub.consultingPrice || null,
            consultingCriteria: sub.consultingCriteria || null,
            addons: sub.addons
              ? {
                  create: sub.addons.map((a) => ({
                    name: a.name,
                    price: a.price,
                    priceType: a.priceType,
                  })),
                }
              : undefined,
            formFields: sub.formFields
              ? {
                  create: sub.formFields.map((f) => ({
                    label: f.label,
                    fieldType: f.fieldType,
                    required: f.required,
                    placeholder: f.placeholder || null,
                    helpText: f.helpText || null,
                    order: f.order,
                    options: f.options || null,
                  })),
                }
              : undefined,
          })),
        },
      },
      include: {
        subcategories: {
          include: { addons: true, formFields: true },
        },
      },
    });

    console.log(`  Created category: ${category.name} (${category.subcategories.length} subcategories)`);
  }

  console.log('Seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
